# This class represents an entry in the look-up table used to reverse translate
# a given log message. Here, we take as input a parsed-out POT file entry 
# (generated by POParser) and create a map of ParameterizedString => ParameterizedString
# entries (Foreign Message => Translation).
class POEntry
  def initialize(pot_entry)
    msgid_part, msgstr_part = pot_entry
    translation = msgid_part["msgid#{"_plural" if msgid_part.size > 1}"]
    @translations = msgstr_part.values.map { |value| [value, translation] }.to_h
  end

  # This method does the reverse translation. Here we find the first matching
  # msgstr in our translation map, extract out the parameters, translate it to
  # its original form, and then put the parameters back in. Note that only part
  # of the message might be translated.
  def reverse_translate(msg)
    matching_str = @translations.keys.find { |k| k.match(msg) }
    return msg unless matching_str
    pre, param_values, post = matching_str.match(msg)
    pre + @translations[matching_str].substitute_values(param_values) + post
  end
end
